[package]
name = "sthp"
version = "0.2.0"
authors = ["Karan Gauswami <karangauswami.dev@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-util = "0.3"
http = "0.2"
hyper = { version = "0.14", features = ["http1", "server", "tcp", "client"] }
structopt = { version = "0.3", default-features = false }
tokio-socks = "0.5"
tokio = { version = "1.13", features = ["macros", "rt-multi-thread"] }
anyhow = "1.0"
hyper-socks2 = { version = "0.6" }
log = "0.4"
env_logger = "0.9"
