[package]
name = "sthp"
version = "0.1.0"
authors = ["Karan Gauswami <karangauswami.dev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-util = "0.3.8"
http = "0.2.2"
hyper = { version = "0.14", features = ["http2", "server", "tcp"] }
structopt = { version = "0.3", default-features = false }
tokio-socks = "0.5"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
color-eyre = { version = "0.5", default-features = false }
