[package]
name = "sthp"
version = "0.1.0"
authors = ["Karan Gauswami <karangauswami.dev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-util = "0.3.6"
http = "0.2.1"
hyper = "0.13.8"
structopt={version="0.3.20",default-features=false}
tokio-socks = "0.3.0"
tokio={version="0.2",features=["macros"]}
color-eyre ={version= "0.5.6",default-features=false}
