[package]
name = "sthp"
version = "0.1.0"
authors = ["Karan Gauswami <karangauswami.dev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-util= "0.3.15"
http = "0.2.4"
hyper = {version="0.14.9", features = ["full"]}
structopt = { version="0.3.21", default-features=false}
tokio-socks = "0.5.1"
tokio = {version="1.7.1",features=["macros","rt-multi-thread"]}
color-eyre = {version= "0.5.11",default-features=false}
