[package]
name = "sthp"
version = "0.4.0"
license = "MIT"
authors = ["Karan Gauswami <karangauswami.dev@gmail.com>"]
edition = "2021"
categories = ["command-line-utilities"]
description = "Convert Socks5 proxy into Http proxy"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = { version = "0.6", default-features = false }
futures-util = "0.3"
http = "0.2"
hyper = { version = "0.14", features = ["http1", "server", "tcp", "client"] }
clap = { version = "4", features = ["derive"] }
tokio-socks = "0.5"
tokio = { version = "1.28", features = ["macros", "rt-multi-thread"] }
hyper-socks2 = { version = "0.8" }
log = "0.4"
env_logger = "0.10"
